kind: pipeline
name: default

steps:
- name: test
  image: ubuntu:trusty
  commands:
  - ./prepare.sh
  - export PATH=/root/.cargo/bin:$PATH
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export PATH=$HOME/.local/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - echo $HOME
  - pwd
  - ./install_zeromq.sh
  - ./install_kcov.sh
  - cargo build
  - cargo test
 

